# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8dd3b2dcdad3f6ae6bdb78e9eee2796286a2fcea2d9877e7198cd40c6ace346aec12efee75e6b2190a2e6190206c2426a3f5a7b1fece6ea20a2865d06e10293

test:
  secret_key_base: 5330c5f6c0c1714c8632e193ef5b6ed4cb08afb512d0dc367a80b29b8590d8e4ef2073c0990d2566fd29228ba0a32da345dfb7461340a5d384884b50d3786225

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
